### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by neilferreri** [built1n/rastercarve-live#14]
![image](https://user-images.githubusercontent.com/2966894/156903750-9ded0ad6-c122-4e2a-8f4c-c75a7b827356.png)
Is there a way to run the web version locally?

**Comment by built1n** [comment]
Fixed - thanks for letting me know. I set it on a cron job now; shouldn't reoccur.

And yes, you can run your own local instance. I haven't written up the instructions, but it should just be a matter of `docker build`.

**Comment by neilferreri** [comment]
Thanks!
