### ISSUE TITLE
rastercarve.live still active?

### ISSUE THREAD

**Issue by neilferreri** [built1n/rastercarve-live#19]
Hi,
Is `https://rastercarve.live/` still active?
Can I host it locally on my PC?

Thanks!

**Comment by built1n** [comment]
Hi @neilferreri, looks like something funky is happening with my hosting provider... I'll take a look.

EDIT: It's looking like something a bit more complex than I'd hope. This will probably be down for the next few days at the minimum, until I can look at it more.

Until then, you can host your own instance if you have a Docker environment set up. See https://docs.docker.com/get-started/02_our_app/#build-the-apps-container-image for how to run it.

**Comment by neilferreri** [comment]
Hey @built1n,
Any chance you'll get this up and running again?
Thanks!

**Comment by built1n** [comment]
Hi @neilferreri,

I took a deeper dive, and looks like there's some bitrot going on w.r.t. Node packages... not something very exciting to fix. I'm probably not going to have time to fix it in the near term; if you're interested, try building the Docker image and see if you can patch it.

**Comment by built1n** [comment]
I have fixed the build issues, and the site is now back up and running: https://rastercarve.live/
